### ISSUE TITLE
User Story (4): Multi-Line-Code support

### ISSUE THREAD

**Issue by jakobwischner** [HPI-SWA-Teaching/SWT17-Project-12#13]
As a user I want to be able to write multiple lines of code and want to see them getting executed line per line.
AC: It's possible to write more than one line of code and let all written lines execude line per line.

**Comment by djdj10x10** [comment]
Worum geht es hier? :D Bevor ich eine falsche Userstory schreibe? Dass wir mehrere Zeilen verwenden können, um die Maus zu steuern – diese demnach gleichzeitig nacheinander ausgeführt werden können?

**Comment by No-Name007** [comment]
Ich würde sagen, dass sich das auf die Ausführung mehrerer Codezeilen bezog, wie du das schon sagtest. Und eventuell dann eben mit einer Verzögerung zwischen den Codeblöcken, um dem Benutzer zu zeigen, was seine Eingaben schrittweise tun.
