### ISSUE TITLE
User Story (5): Progress Bar

### ISSUE THREAD

**Issue by jakobwischner** [HPI-SWA-Teaching/SWT17-Project-12#3]
Als Teilnehmer möchte ich jederzeit sehen, wo ich mich im Kurs befinde, um einen zeitlichen Überblick zu erhalten. Eine prozentuelle Anzeige meines Fortschritts erleichtert den Überblick.

Acceptance Criteria:

1. Das schließt sowohl die Position innerhalb der einzelnen Units als auch der Subunits mit ein.
2. Die Anzeige ist im oberen Bereich des Toolbuilders platziert

**Comment by djdj10x10** [comment]
Redundant
