### ISSUE TITLE
User Story (4): Lesson 2 aufbauen (for Schleifen, Eat Cheese Methode, mehrere Käsestücken)

### ISSUE THREAD

**Issue by jakobwischner** [HPI-SWA-Teaching/SWT17-Project-12#30]
As a user I want to have a second lesson in which I have to move the mouse to some different pieces of cheese and let the mouse eat the cheese with the `eat` method (`mouse eat: cheese`). This will introduce methods with parameters.

AC: Lesson is finished and works

**Comment by djdj10x10** [comment]
Sollen wir hier nicht lieber ein Labyrinth hinzufügen, anstatt nur mehrere Käsestücke

**Comment by jakobwischner** [comment]
Die Idee war, das wir in der ersten Stufe nur ein Ziel markieren, wo die Maus hin bewegt werden muss (farbiges Kästchen, kein Käse) und wir in der zweiten dann eben 3 Stück Käse oder so verteilt werden müssen und da dann zum ersten Mal eine Methode mit Parameter genutzt werden muss. Also `mouse eat: cheese`. So wird dann in der zweiten Stufe nicht primär das Spielfeld komplizierter, sondern eben der Squeak Anteil.
