### ISSUE TITLE
User Story (1): Lesson "Parameters"

### ISSUE THREAD

**Issue by No-Name007** [HPI-SWA-Teaching/SWT17-Project-12#42]
Acceptance Criteria:

* Benutzer soll Maus mithilfe von "moveLeft/...: amount" zum Ziel bewegen

**Comment by jakobwischner** [comment]
Die Methoden `moveLeftByAmount:`, `moveRightByAmount:`, `moveUpByAmount:` und `moveDownByAmount:` kennt die Maus schon.
