### ISSUE TITLE
User Story: Labyrinth

### ISSUE THREAD

**Issue by djdj10x10** [HPI-SWA-Teaching/SWT17-Project-12#45]
Als Benutzer möchte ich ein in der dritten Lesson ein Labyrinth, durch das ich die Maus steuern kann. 

Acceptance Criteria:
- Conditionals Loops... Die Maus bewegt sich so lange in eine Richtung, bis sie auf ein Hinderniss stößt(, aber ist hier wirklich eine Pflicht conditional Loops zu verwenden?)(Alternativ so etwas wie dreimal gegen eine Wand laufen, bis die Wand nachgibt. Und zwar in einem Codeschritt. Dann bräuchten wir wirklich Conditional Loops)
- Das Labyrinth ist auf dem Kanten des Grids errichtet. Und verhindert, dass die Maus zum nächstgelegenen Feld kommen kann. Das Labyrinth ist statisch. (Daher sollte die Maus für diese Lesson nur an einem Ort spawnen können.)
- Das Labyrinth kann durch den Benutzer wie das Maus Objekt verändert und bewegt werden. Zum Beispiel könnte die Maus am Anfang eingesperrt sein. 
- Ein weiteres Element ist es die Maus schrumpfen (und wachsen zu lassen) zu lassen, um durch Pfade des Labyrinthes zu steuern. (Alternativ könnte die Maus auch springen?!)

**Comment by usame-algan** [comment]
Duplikat zu #47

**Comment by jakobwischner** [comment]
muss das labyrinth auf den kanten sein? könnte ja auch so gebaut werden, wie jetzt in lesson 3 die unterbrechungen. davon hängt natürlich auch ab, wie aufwendig es ist, das zu implementieren.

**Comment by No-Name007** [comment]
Das Labyrinth werden wir genauso wie in Lesson 3 bauen, dass die Mauern eigene Felder sind.

Hier würde ich 5 schätzen, da das Labyrinth genaut werden müsste und wir denke mal auch ein größeres Grid verwenden wollen
