### ISSUE TITLE
User Story (4): Objektattribute

### ISSUE THREAD

**Issue by usame-algan** [HPI-SWA-Teaching/SWT17-Project-12#47]
Als Nutzer möchte in Squeak lernen, das Objekte Attribute haben, und diese veränderbar sind. Dafür muss die Maus durch ein Labyrinth gesteuert werden, und verschiedene farbliche Tore passieren. Die Maus kann die Tore nur passieren, wenn sie dieselbe Farbe hat.

Acceptance Criteria: 
 1. Die Maus ist mit einem Farbattribut ausgestattet, das veränderbar ist
 2. Die Tore überprüfen, ob das richtige Farbattribut vorliegt, wenn die Maus passieren möchte

**Comment by jakobwischner** [comment]
vllt. 4 stunden? je nach dem, ob die begrenzungen auf den linien oder auf den feldern sein sollen. auf den feldern kann man es ja einfach aus lesson 3 übernehmen und erweitern.

**Comment by No-Name007** [comment]
Würde 3 schätzen. Auf den Feldern werden denke mal Bilder dann liegen (offen zu + verschiedene Farben).
