### ISSUE TITLE
User Story (6): Objektidentität

### ISSUE THREAD

**Issue by usame-algan** [HPI-SWA-Teaching/SWT17-Project-12#48]
Als Nutzer möchte ich die Maus Klonen können, um in Squeak über Objektidentitäten zu lernen. Die Mäuse sollen sich gegenseitig Tore öffnen, sodass eine der Mäuse zum Ziel gelangen kann.

Acceptance Criteria:
 1. Neben der Maus kann durch den Clone-Vorgang ein zweite Maus angelegt werden. 
 2. Die beiden Mäuse können unterschiedlich angesteuert werden

**Comment by jakobwischner** [comment]
vllt. 3 stunden?

**Comment by No-Name007** [comment]
Würde für beide Lessons 5 sagen (2 für die erste und 3 für die zweite)

Wollten wir das nicht in zwei Lessons unterteilen? Zuerst klonen und dann zu zwei unterschiedlichen Punkten laufen und danach noch eine solche Lesson?
