### ISSUE TITLE
User Story (6): Messages

### ISSUE THREAD

**Issue by usame-algan** [HPI-SWA-Teaching/SWT17-Project-12#49]
Als Nutzer möchte ich mehr über die drei unterschiedlichen Message-Prinzipien in Squeak lernen(Unary, Binary und Keyword Messages). Dafür vergleiche ich Codezeilen in einem Multiple-Choice Test und ordne sie mittels der Erklärung im Instruction-Window zu.

Acceptance Criteria:
1. Aussagen lassen sich mittels eines Häkchens ankreuzen
2. Auswahl lässt sich auf Richtigkeit überprüfen

**Comment by jakobwischner** [comment]
4 stunden?

**Comment by No-Name007** [comment]
Hier würde ich evtl 6 vorschlagen. Es gibt das mit den Radio Buttons noch nicht im Framework und müsste implementiert werden.

Außerdem sind das dann hier 3 oder mehr kleine Lessons denke
