### ISSUE TITLE
User Story: Explanations & Instruction

### ISSUE THREAD

**Issue by jakobwischner** [HPI-SWA-Teaching/SWT17-Project-12#5]
Als Teilnehmer möchte ich ein Fenster haben, dass mir Schritt für Schritt erklärt, was ich momentan mit der Codebox tun soll. Dieses Fenster sollte Interaktions- und Fortschrittsbasiert arbeiten: Das heißt, wenn ich einen Teil der Subunit erfüllt habe, wird die Aufgabenstellung angepasst. Die Anweisungen sollten hilfereich aber nicht zu ausführlich sein. Sie sollten mich dabei unterstützen, wie ich mittels des Infoscreens die richtigen Codeanweisungen eingeben kann.

Acceptance Criteria:

1. Interaktive Zusammenarbeit mit dem Morph Screen und der Codebox zusammenarbeiten
2. Wenn die Aufgabenstellung erfüllt ist, kommt eine neue Instruktion(, bzw. wird die Subunit als abgeschlossen markiert)
3. Scrollbar für den Erklärungstext

**Comment by djdj10x10** [comment]
Redundant mit: "User Story (3): Add Info Text for first Lesson"

**Comment by djdj10x10** [comment]
Navigation (verbessern, BackToMenuButton) ist der Gegenpart, der dann auf verbessern erweitert wurde... Da hier mehrere Iterationen benötigt werden, um das Infowindow wirklich fertigzustellen
