### ISSUE TITLE
User Story (10): InfoWindow

### ISSUE THREAD

**Issue by jakobwischner** [HPI-SWA-Teaching/SWT17-Project-12#6]
Als Teilnehmer möchte ich die Methoden und Parameter der für die Aufgabengestellung relevanten Klassen einsehen können, um zu wissen, mit welchen Codebestandteilen ich im Codefeld arbeiten soll.

Acceptance Criteria:

1. Das Info Window ist zu und aufklappbar.
2. Es ist direkt mit einem Button unter dem Codefeld zugreifbar.
3. Das ? Symbol markiert das InfoWindow.
4. Das InfoWindow besteht aus drei Teilen: Den (Sub)klassen, den Methoden und den Beschreibungen der Methoden

**Comment by djdj10x10** [comment]
War in einer Iteration als wir noch gar nicht GitHub benutzt haben!!!!!!
