### ISSUE TITLE
User Story (4): Lockdown

### ISSUE THREAD

**Issue by jakobwischner** [HPI-SWA-Teaching/SWT17-Project-12#7]
Als Nutzer möchte ich, dass ich, dass jegliche überflüssigen Optionen im Image für mich nicht zugänglich sind, damit ich das Image nicht versehentlich zerstören kann.

Acceptance Criteria: Die Head Leiste ist weg, das Fenster läuft im Full Screen, (das Fenster kann nicht mehr inspiziert werden).

**Comment by djdj10x10** [comment]
Wird erst angewendet, wenn alles fertig ist...
