### ISSUE TITLE
User Story: Restrict Mouse Access

### ISSUE THREAD

**Issue by jakobwischner** [HPI-SWA-Teaching/SWT17-Project-12#9]
Als Teilnehmer möchte ich eine klar eingegrenzte Bewegungsumgebung für die Mouse haben. Die Maus sollte diese nicht verlassen dürfen, bzw. einen Fehler melden, wenn sie verlassen wird.

Acceptance Criteria: Mouse Boundaries sind umgesetzt

**Comment by usame-algan** [comment]
duplikat zu bounds kann gelöscht werden?
